In [1]:
import urllib

params = 'DRIVER={ODBC Driver 13 for SQL Server};' \
         'SERVER=localhost;' \
         'PORT=1433;' \
         'DATABASE=DbAsftPortal;' \
         'UID=sa;' \
         'PWD=aSj#14776$10036%mM&;'
            
params = urllib.parse.quote_plus(params)

from sqlalchemy import create_engine

db = create_engine('mssql+pyodbc:///?odbc_connect=%s' % params)

import pandas as pd

sql = '''
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_CATALOG='DbAsftPortal'
'''

pd.read_sql_query(sql, db)

                                TABLE_NAME
0                           knox_authtoken
1                         tbl_library_book
2                  tbl_library_book_author
3               tbl_library_book_publisher
4                    tbl_library_book_type
5                  tbl_library_loaned_book
6                   tbl_meeting_cater_type
7                    tbl_meeting_equipment
8                      tbl_meeting_request
9                         tbl_meeting_room
10                   tbl_meeting_room_type
11              tbl_meeting_room_equipment
12          tbl_meeting_request_cater_type
13                 tbl_resturaunt_day_meal
14                       django_migrations
15           tbl_resturaunt_guest_day_meal
16                     django_content_type
17                     tbl_resturaunt_meal
18                         auth_permission
19  tbl_resturaunt_guest_day_meal_junction
20                              auth_group
21        tbl_resturaunt_employee_day_meal
22                  auth_group_permissions
23                               auth_user
24                        auth_user_groups
25              auth_user_user_permissions
26                          django_session
27                       tbl_survey_answer
28                     tbl_survey_question
29                       tbl_survey_survey
30                        django_admin_log
31                  tbl_survey_user_answer
32                   tbl_survey_department
33                        tbl_base_company
34                     tbl_base_department
35                          tbl_doctorType
36                    tbl_base_jobPosition
37                          tbl_surveyType
38                        tbl_base_project
39                   tbl_base_notification
40                       tbl_base_employee
41           tbl_meeting_request_equipment
42                    tbl_doc_appointments
43                             tbl_doctors
44               tbl_doc_schedule_weekdays
45                   tbl_doc_schedule_days
46                  tbl_doc_patients_files
47                        tbl_doc_patients
48               tbl_doc_appointment_times

In [23]:
import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'rest.settings')
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"
django.setup()

from datetime import date, datetime, timedelta
from resturaunt.models import Resturaunt_Meal, Resturaunt_Day_Meal, Resturaunt_Employee_Day_Meal

try:
    import json
    personelMealDays = [
		{"employee":1347,"resturaunt_day_meal":296},
		{"employee":1347,"resturaunt_day_meal":301},
		{"employee":1347,"resturaunt_day_meal":307},
		{"employee":1347,"resturaunt_day_meal":312},
		{"employee":1347,"resturaunt_day_meal":317},
		{"employee":1347,"resturaunt_day_meal":322},
		{"employee":1347,"resturaunt_day_meal":327},
		{"employee":1347,"resturaunt_day_meal":332},
		{"employee":1347,"resturaunt_day_meal":337},
		{"employee":1347,"resturaunt_day_meal":342},
		{"employee":1347,"resturaunt_day_meal":347},
		{"employee":1347,"resturaunt_day_meal":352},
		{"employee":1347,"resturaunt_day_meal":359}
		]
    editMood = True

    employee_id = personelMealDays[0]['employee']

    currentdate = datetime.today()
    y = currentdate.year
    m = currentdate.month-1
    d = currentdate.day
    startdate = ""
    enddate = ""
    if(m == 1):
        startdate += str(y) 
        startdate += "-01" if (d < 21) else "-02" 
        startdate += "-21" if (d < 21) else "-20"
        enddate += str(y) 
        enddate += "-02" if (d < 21) else "-03" 
        enddate += "-19" if (d < 21) else "-20"
    elif(m == 2):
        startdate += str(y) 
        startdate += "-02" if (d < 20) else "-03" 
        startdate += "-20" if (d < 20) else "-21"
        enddate += str(y) 
        enddate += "-03" if (d < 20) else "-04" 
        enddate += "-20" if (d < 20) else "-20"
    elif(m == 3):
        startdate += str(y) 
        startdate += "-03" if (d < 21) else "-04" 
        startdate += "-21" if (d < 21) else "-21"
        enddate += str(y) 
        enddate += "-04" if (d < 21) else "-05" 
        enddate += "-21" if (d < 21) else "-21"
    elif(m == 4):
        startdate += str(y) 
        startdate += "-04" if (d < 21) else "-05" 
        startdate += "-21" if (d < 21) else "-22"
        enddate += str(y) 
        enddate += "-05" if (d < 21) else "-06" 
        enddate += "-21" if (d < 21) else "-21"            
    elif(m == 5):
        startdate += str(y) 
        startdate += "-05" if (d < 22) else "-06" 
        startdate += "-22" if (d < 22) else "-22" 
        enddate += str(y) 
        enddate += "-06" if (d < 22) else "-07" 
        enddate += "-21" if (d < 22) else "-22"            
    elif(m == 6):
        startdate += str(y) 
        startdate += "-06" if (d < 22) else "-07" 
        startdate += "-22" if (d < 22) else "-23" 
        enddate += str(y) 
        enddate += "-07" if (d < 22) else "-08" 
        enddate += "-22" if (d < 22) else "-22"            
    elif(m == 7):
        startdate += str(y) 
        startdate += "-07" if (d < 23) else "-08" 
        startdate += "-23" if (d < 23) else "-23" 
        enddate += str(y) 
        enddate += "-08" if (d < 23) else "-09" 
        enddate += "-22" if (d < 23) else "-22"            
    elif(m == 8):
        startdate += str(y) 
        startdate += "-08" if (d < 23) else "-09" 
        startdate += "-23" if (d < 23) else "-23" 
        enddate += str(y) 
        enddate += "-09" if (d < 23) else "-10" 
        enddate += "-22" if (d < 23) else "-22"
    elif(m == 9):
        startdate = str(y) 
        startdate += "-09" if (d < 23) else "-10" 
        startdate += "-23" if (d < 23) else "-23" 
        enddate += str(y) 
        enddate += "-10" if (d < 23) else "-11" 
        enddate += "-22" if (d < 23) else "-21"            
    elif(m == 10):
        startdate += str(y) 
        startdate += "-10" if (d < 23) else "-11" 
        startdate += "-23" if (d < 23) else "-22" 
        enddate += str(y) 
        enddate += "-11" if (d < 23) else "-12" 
        enddate += "-21" if (d < 23) else "-21"            
    elif(m == 11):
        startdate += str(y) 
        startdate += "-11" if (d < 22) else "-12" 
        startdate += "-22" if (d < 22) else "-22" 
        enddate += str(y) 
        enddate += "-12" if (d < 22) else "-01" 
        enddate += "-21" if (d < 22) else "-20"
    elif(m == 12):
        startdate += str(y) 
        startdate += "-12" if (d < 22) else "-01" 
        startdate += "-22" if (d < 22) else "-21"
        enddate += str(y) 
        enddate += "-01" if (d < 22) else "-02" 
        enddate += "-20" if (d < 22) else "-19"             

    if(editMood):
        print('add')
        print('currentdate: ', currentdate)
        print('startdate: ', startdate)
        print('enddate: ', enddate)
        
        dt = currentdate + timedelta(days=3)
        next3DaysDate = dt.date()
        print('next3DaysDate: ', next3DaysDate)
        
        result = Resturaunt_Employee_Day_Meal.objects.filter(
            employee=employee_id, 
            resturaunt_day_meal__date__gte=startdate, 
            resturaunt_day_meal__date__lte=enddate)

        mealDays = Resturaunt_Day_Meal.objects.filter(date__gte=startdate, date__lte=enddate).filter(date__gt=next3DaysDate)
        mealDayNo = mealDays.count()
        firstMealDay = mealDays.first()
        mealsDayNo =  Resturaunt_Day_Meal.objects.filter(date__exact=firstMealDay.date).count()
        mealSelectedNo = (mealDayNo // mealsDayNo)

        print('len(result): ', len(result))
        print('len(personelMealDays): ', len(personelMealDays))
        print('mealSelectedNo: ', mealSelectedNo)
        
        if(len(result) == 0 and len(personelMealDays) == mealSelectedNo):
            objs = []
            for pmd in personelMealDays:
                obj = Resturaunt_Employee_Day_Meal(
                    employee_id=pmd['employee'], 
                    resturaunt_day_meal_id=pmd['resturaunt_day_meal'])
                objs.append(obj)
            Resturaunt_Employee_Day_Meal.objects.bulk_create(objs)   
        for item in objs:
            print(item.id, ' ,  ', item.employee, ' ,  ', item.resturaunt_day_meal)
            print('----------------------------------')
        print('addition done')
        result = (Resturaunt_Employee_Day_Meal.objects.filter(employee=employee_id, 
            resturaunt_day_meal__date__gte=startdate, resturaunt_day_meal__date__lte=enddate).values('id', 'employee', 'resturaunt_day_meal'))

        for item in result:
            print(item)
            print('----------------------------------')
            
    else:
        print('edit')        
        objs = []
        for pmd in personelMealDays:
            obj = Resturaunt_Employee_Day_Meal.objects.get(id=pmd['id'])
            obj.resturaunt_day_meal_id = pmd['resturaunt_day_meal']
            objs.append(obj)
        
        for item in objs:
            print(item)
            print('----------------------------------')
        Resturaunt_Employee_Day_Meal.objects.bulk_update(objs, ['resturaunt_day_meal'])     

        result = (Resturaunt_Employee_Day_Meal.objects.filter(employee=employee_id, 
            resturaunt_day_meal__date__gte=startdate, resturaunt_day_meal__date__lte=enddate).values('id', 'employee', 'resturaunt_day_meal'))                         

        for item in result:
            print(item)
            print('----------------------------------')
            
except Exception as e:
    print(e)     

        
print('==================================================')
print('id: ', '      resturaunt_day_meal:    ')    
print('==================================================')
for item in objs:    
    print(item.id, '   ', item.resturaunt_day_meal)
    print('-------------------------------------')
# Resturaunt_Employee_Day_Meal.objects.bulk_update(objs, ['resturaunt_day_meal'])

add
currentdate:  2021-09-29 11:30:02.164024
startdate:  2021-09-23
enddate:  2021-10-22
next3DaysDate:  2021-10-02
len(result):  0
len(personelMealDays):  13
mealSelectedNo:  13
None  ,   Employee object (1347)  ,   Resturaunt_Day_Meal object (296)
----------------------------------
None  ,   Employee object (1347)  ,   Resturaunt_Day_Meal object (301)
----------------------------------
None  ,   Employee object (1347)  ,   Resturaunt_Day_Meal object (307)
----------------------------------
None  ,   Employee object (1347)  ,   Resturaunt_Day_Meal object (312)
----------------------------------
None  ,   Employee object (1347)  ,   Resturaunt_Day_Meal object (317)
----------------------------------
None  ,   Employee object (1347)  ,   Resturaunt_Day_Meal object (322)
----------------------------------
None  ,   Employee object (1347)  ,   Resturaunt_Day_Meal object (327)
----------------------------------
None  ,   Employee object (1347)  ,   Resturaunt_Day_Meal object (332)
----------------------------------
None  ,   Employee object (1347)  ,   Resturaunt_Day_Meal object (337)
----------------------------------
None  ,   Employee object (1347)  ,   Resturaunt_Day_Meal object (342)
----------------------------------
None  ,   Employee object (1347)  ,   Resturaunt_Day_Meal object (347)
----------------------------------
None  ,   Employee object (1347)  ,   Resturaunt_Day_Meal object (352)
----------------------------------
None  ,   Employee object (1347)  ,   Resturaunt_Day_Meal object (359)
----------------------------------
addition done
{'id': 21053, 'employee': 1347, 'resturaunt_day_meal': 296}
----------------------------------
{'id': 21054, 'employee': 1347, 'resturaunt_day_meal': 301}
----------------------------------
{'id': 21055, 'employee': 1347, 'resturaunt_day_meal': 307}
----------------------------------
{'id': 21056, 'employee': 1347, 'resturaunt_day_meal': 312}
----------------------------------
{'id': 21057, 'employee': 1347, 'resturaunt_day_meal': 317}
----------------------------------
{'id': 21058, 'employee': 1347, 'resturaunt_day_meal': 322}
----------------------------------
{'id': 21059, 'employee': 1347, 'resturaunt_day_meal': 327}
----------------------------------
{'id': 21060, 'employee': 1347, 'resturaunt_day_meal': 332}
----------------------------------
{'id': 21061, 'employee': 1347, 'resturaunt_day_meal': 337}
----------------------------------
{'id': 21062, 'employee': 1347, 'resturaunt_day_meal': 342}
----------------------------------
{'id': 21063, 'employee': 1347, 'resturaunt_day_meal': 347}
----------------------------------
{'id': 21064, 'employee': 1347, 'resturaunt_day_meal': 352}
----------------------------------
{'id': 21065, 'employee': 1347, 'resturaunt_day_meal': 359}
----------------------------------
==================================================
id:        resturaunt_day_meal:
==================================================
None     Resturaunt_Day_Meal object (296)
-------------------------------------
None     Resturaunt_Day_Meal object (301)
-------------------------------------
None     Resturaunt_Day_Meal object (307)
-------------------------------------
None     Resturaunt_Day_Meal object (312)
-------------------------------------
None     Resturaunt_Day_Meal object (317)
-------------------------------------
None     Resturaunt_Day_Meal object (322)
-------------------------------------
None     Resturaunt_Day_Meal object (327)
-------------------------------------
None     Resturaunt_Day_Meal object (332)
-------------------------------------
None     Resturaunt_Day_Meal object (337)
-------------------------------------
None     Resturaunt_Day_Meal object (342)
-------------------------------------
None     Resturaunt_Day_Meal object (347)
-------------------------------------
None     Resturaunt_Day_Meal object (352)
-------------------------------------
None     Resturaunt_Day_Meal object (359)
-------------------------------------

In [37]:
from ldap3 import Server, Connection, ALL, NTLM, SUBTREE
import re, io
from django.contrib.auth.models import User

username = 'ne.nasrollahi'
password = '789@qwe'
LDAP_URL = 'dc.asft.co:389'
domain_user = 'asft\\' + username
# tls_configuration = Tls(validate=ssl.CERT_REQUIRED, version=ssl.PROTOCOL_TLSv1)
# server = Server(LDAP_URL, use_ssl=True, tls=tls_configuration)
try:
    server = Server(LDAP_URL, get_info=ALL)
    conn = Connection(server, user=domain_user, password=password, authentication=NTLM, auto_bind=True)

    base = '''dc=asft,dc=co'''
    criteria = '(&(objectCategory=user)(sAMAccountName='+ username+'))'
    attributes = ['sAMAccountName', 'givenName', 'sn', 'mail', 'userAccountControl', 'thumbnailPhoto']
    conn.search(base, criteria, attributes=attributes)
    # conn.search(search_base='dc=asft,dc=co', search_filter=f'(sAMAccountName={username})',search_scope=SUBTREE, attributes=['sAMAccountName'])


    if len(conn.response) != 0:
        entity = conn.response[0]

        pattern = re.compile(r'^[a-z|A-Z]+\.[a-z|A-Z|\s]+$')
        if('attributes' in entity and pattern.match(str(entity['attributes']['sAMAccountName']))):
            print('username = ', entity['attributes']['sAMAccountName'])
            print('first_name = ', entity['attributes']['givenName'])
            print('last_name = ', entity['attributes']['sn'])
            print('email = ', entity['attributes']['mail'])
            print('thumbnailPhoto = ', entity['attributes']['thumbnailPhoto'])
except Exception as e:
    print(e)
    

#         username = entity['attributes']['sAMAccountName']
#         first_name = entity['attributes']['givenName']
#         last_name = entity['attributes']['sn']
#         email = entity['attributes']['mail']
#         thumbnailPhoto = entity['attributes']['thumbnailPhoto']        
        
#         is_active = 0 if(entity['attributes']['userAccountControl'] == 66050 or entity['attributes']['userAccountControl'] == 514) else 1
#         print('is_active = ', is_active)
        
#         try:
#             print('1')
#             image_name = '/files/employee_pix/{0}.jpg'.format(username)
#             print('1.5')
#             # Update the user -- this allows for name changes etc, using username as the key.
#             user, user_created = User.objects.update_or_create(username=username, 
#                 defaults={'email': email, 'first_name': first_name, 'last_name': last_name, 'is_active': is_active})
#             print('2')
#             if user_created:
#                 # Set an unusable password -- django-auth-ldap handles this, anyway.   'user_id':user.id, 
#                 user.set_unusable_password()
#                 user.save()
#                 # first_name__exact=first_name, last_name__exact=last_name      , picture=thumbnailPhoto
#             print('3')
#             employees = Employee.objects.filter(user_id__exact=user.id)
#             if(len(employees) == 0):
#                 print('4')
#                 employee = Employee.objects.create(first_name=first_name, last_name=last_name, email=email, user_id=user.id, gender=False)     
#                 if(len(thumbnailPhoto)>0):
#                     buffer = io.BytesIO()
#                     buffer.write(thumbnailPhoto)
#                     image_file = InMemoryUploadedFile(buffer, None, '{0}.jpg'.format(username), 'image/jpg', buffer.getbuffer().nbytes, None)
#                     employee.picture.save(image_name, image_file)   
#             else:
#                 print('5')
#                 if(len(employees) > 1):
#                     employees[1].delete()
#                 if((employees[0].picture == None or employees[0].picture == []) and len(thumbnailPhoto)>0):
#                     buffer = io.BytesIO()
#                     buffer.write(thumbnailPhoto)
#                     image_file = InMemoryUploadedFile(buffer, None, '{0}.jpg'.format(username), 'image/jpg', buffer.getbuffer().nbytes, None)
#                     employees[0].picture.save(image_name, image_file)   

#         except Exception as e:
#             print(e)

username =  Ne.Nasrollahi
first_name =  Nemat
last_name =  Nasrollahi
email =  []
thumbnailPhoto =  []